### ISSUE TITLE
Agregar el juego Crossfire

### ISSUE THREAD

**Issue by Darkfleyker** [VNNGYN/Windows-RT-8.1-Development-Tool#10]
Mucho gusto, acabo de descubrir tu tutorial de como correr programas y juegos fuera de la tienda Windows en Surface RT. Aun que hay muy pocas aplicaciones, se que poco a poco van a ir agregando mas. Por eso me gustaría que agregarán un juego llamado Crossfire ya que ese es mi juego favorito, aquí te dejaré el link del juego: http://es.crossfire.z8games.com/download.html        gracias :)

El juego es genero shooter fps zombis

**Comment by VNNGYN** [comment]
Hey,

I am afraid I can't help you with that. First of all, the game you linked in your message is not open-source. Secondly, I don't port applications to Windows RT 8.1.

I am truly sorry to disappoint you.

Kind regards,
VNNGYN
