### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Askmewho** [VNNGYN/Windows-RT-8.1-Development-Tool#11]
Hi I am interested on obtain office 2013 rt and i cant find a proper windows rt image than include it. my idea its to test office rt on wine ARM on raspberry pi 3. Ive already tested other native arm software under wine like rufus.  could you supply me a torrent or anything to test?

**Comment by VNNGYN** [comment]
Thank you for your message. Unfortunately, I don't have anything related to Windows RT anymore except for the Windows RT 8.1 Development Tool.
