### ISSUE TITLE
Stubborn SurfaceRT 32GB

### ISSUE THREAD

**Issue by Fenidean** [VNNGYN/Windows-RT-8.1-Development-Tool#12]
Hello. I know the project is discontinued but i want to try to use my surface a bit more. I got it just recently and since then I am trying to jailbreak it. I run the tool many times to uninstall infected updates until it just keep restarting with no configuring updates. But it just won´t go to test mode. I even tried to run powershell in admin and typed bcdedit /set '{current}' loadoptions '/TŅSTSIGNING' restarted but still nothing. I just don´t know what I am missing. 
Microsoft Surface RT 32GB 8.1 Up to date (uninstalled infected updates)

**Comment by VNNGYN** [comment]
Hey Fenidean,

Sorry for my late response. I will look into this. Stay tuned.

Kind regards,
VNNGYN

**Comment by Fenidean** [comment]
No problem I appreciate the effort as it is abandoned project 
Will wait for response 

Best regards 
Fenidean

**Comment by VNNGYN** [comment]
Hello Fenidean,

I just removed all _Infected Updates_  and I was able to enter _Test Mode_. You may try removing them again. Good luck.

Kind regards,
VNNGYN

**Comment by Fenidean** [comment]
still not working for me. Might there be a problem with logging in as microsoft account? Im concidering complete reset and redo of all things. Will try to redownload infected updates and redo the process again with manually erasing updates.

**Comment by VNNGYN** [comment]
Hey Fenidean,

Sorry for my late response. That's odd. And no, it has nothing to do with your Microsoft account. I could release a new tool, but I don't do that anymore. You may try removing the _Infected Updates_ again.

Kind regards,
VNNGYN

P.S. You could just add the new _Infected Updates_ to the latest version of the Development Tool by opening it with _Notepad++_.
