### ISSUE TITLE
Is File Recovery Like Recuva possible to port?

### ISSUE THREAD

**Issue by awesomegithub222** [VNNGYN/Windows-RT-8.1-Development-Tool#13]
I don't know how it works but I found my surface RT and wondered if file recovery is possible on it?

**Comment by awesomegithub222** [comment]
Or photorec/Test disk as heard it's open source

**Comment by VNNGYN** [comment]
Dear @awesomegithub222,

This place is meant to answer questions related to the Development Tool. You may ask your question on XDA.

Kind regards,
VNNGYN
