### ISSUE TITLE
MiniVMac on Windows RT

### ISSUE THREAD

**Issue by friedkiwi** [VNNGYN/Windows-RT-8.1-Development-Tool#14]
Link: https://github.com/friedkiwi/minivmac/releases/tag/v0.3

Source included on GH repo. Tested on my surface RT.

**Comment by VNNGYN** [comment]
Sorry for my last response. Added!

**Comment by friedkiwi** [comment]
No worries - you're welcome! I've managed to build a llvm-based MinGW toolchain so it's a lot easier to build open source code now.
