### ISSUE TITLE
Putty

### ISSUE THREAD

**Issue by JamesHawkinss** [VNNGYN/Windows-RT-8.1-Development-Tool#15]
Hey there! I understand that this project is abandoned, but I'm just a bit stuck here.

My Surface has booted into Test Mode, but unfortunately the listed download link for Putty doesn't work. Also, the download link for the signing tool doesn't seem to work either. I can download the source code for it, but not the actual tool itself.

Any help would be greatly appreciated!

**Comment by Qiangong2** [comment]
The sign tool seems to work for, here's the direct link: https://forum.xda-developers.com/attachment.php?attachmentid=3512177&d=1445282135

I can't help with putty, I didn't have it downloaded. Maybe the wayback machine has it? Honestly though, it's so out of date that it's a security risk to use it for anything

**Comment by Qiangong2** [comment]
@JamesHawkinss I checked the official putty site and they have 32 bit ARM builds. I didn't do anything more than boot it up, but it looks like it works. Make sure to download the zip file and sign all the exe files.

**Comment by JamesHawkinss** [comment]
> @JamesHawkinss I checked the official putty site and they have 32 bit ARM builds. I didn't do anything more than boot it up, but it looks like it works. Make sure to download the zip file and sign all the exe files.

Alright, thanks so much!
