### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by futurest1r-zz** [VNNGYN/Windows-RT-8.1-Development-Tool#16]
Just a heads up. I'm in the process of downloading all of the necessary tools and information. Unfortunately, the Google link for more info has stopped working. Best regards, Eric

**Comment by VNNGYN** [comment]
Hello Eric,

What do you mean with "Google link"? 

Kind regards,
VNNGYN

**Comment by futurest1r-zz** [comment]
This one. @

https://github.com/VNNGYN/Windows-RT-8.1-Development-Tool/wiki/Applications-ported-to-Windows-RT-8.1


Eric

**Comment by VNNGYN** [comment]
Hi Eric,

Which link is dead? 

Kind regards,
VNNGYN

**Comment by futurest1r-zz** [comment]
At, https://github.com/VNNGYN/Windows-RT-8.1-Development-Tool/wiki/Applications-ported-to-Windows-RT-8.1, if you scroll down a bit;  I believe its the third paragraph:

"The listed applications have been ported and signed by xda-members. Details about the applications can be found on our best friend Google. If a link doesn't work anymore, please report it here." 

"Google", is the link, and it sent me to an empty Google page.
Hope that clarifies it.

Best regards

**Comment by Qiangong2** [comment]
@futurest1r The link is supposed to send you to Google
