### ISSUE TITLE
I needed some help

### ISSUE THREAD

**Issue by ghost** [VNNGYN/Windows-RT-8.1-Development-Tool#19]
Hi, i am samar, i see that there is that i needed that tools which used in ported for my project, your project was best, but end with windows rt, can you give the tools that you used , i needed for my project, it will very thankful

Samar

**Comment by VNNGYN** [comment]
Dear Samar,

Thank you for your reply. What is it exactly that you need from me?

Kind regards,
VNNGYN

**Comment by ghost** [comment]
Dear VNNGYN,

I have a good reason by which you can reopen your project, there was just windows rt ending, not the project's ending.

Your sincerely,
Samar

**Comment by VNNGYN** [comment]
Dear Samar,

Thank you for your reply. I am afraid to tell you that I am not planning to reboot this project anytime soon. Thereby, I will close this issue.

Have a nice evening.

Kind regards,
VNNGYN

**Comment by ghost** [comment]
Dear VNNGYN,

Shall I tell reason, I installed winehq on my linux proot inside android, for arm,  winehq had created a version which can run arm biniary's exe, like applications for windows ce and windows rt, i tried many ported apps to windows rtp from your repository, and all were installed and working faster than other emulators. If you can reboot project, that will good, just change your target from windows rt to wine arm, i am thinking of a project like win86emu, also if you free, please check my projects, its also related to this, on discord.

Your sincerely,
Samar

**Comment by Qiangong2** [comment]
@SamarJi We have no interest in rebooting the project, nor undertaking a giant thing as wine arm. Sorry.

**Comment by ghost** [comment]
Thanks for a fast comment, but still, i am thinking that another project will good, no wine required, faster than before, may it work. Currently i am working on it.
