### ISSUE TITLE
gdevelop ported to windows rt

### ISSUE THREAD

**Issue by nalcwap** [VNNGYN/Windows-RT-8.1-Development-Tool#2]
is possible port this app to windows rt because i  have android arm and the wine emulator only work the exe if is ported to this , the app is gdevelop , i want the old version WINDOWS (4.0.97)    to be ported not the version 5 because missing some good options, the link to app direct is  https://github.com/4ian/GD/releases/download/4.0.97/gd4097.exe

and the source link is    https://github.com/4ian/GD

the description is
GDevelop is an open-source game creator. It can be used by anyone to create any kind of 2D games.

thanks for help

**Comment by VNNGYN** [comment]
I do not port apps to Windows RT 8.1 anymore. You may try to repost this on XDA.

**Comment by nalcwap** [comment]
ok thanks , i ask there but no answer, what app you use?

2018-07-13 9:46 GMT+01:00 VNNGYN <notifications@github.com>:

**Comment by VNNGYN** [comment]
I used to use Visual Studio 2012/2013/2017

**Comment by nalcwap** [comment]
you know any good tuturial?and is with source code or a setup exe?,im a
newbie, i want convert this app for run in the android emulator because my
tablet is a arm device and not open the exe,,and thanks

2018-07-13 22:57 GMT+01:00 VNNGYN <notifications@github.com>:

**Comment by VNNGYN** [comment]
Go to XDA and look for porting apps to Windows RT.

**Comment by nalcwap** [comment]
it works in any windows the app to convert?my friend pc is a windows 10,64
, he need only the visual studio to port the exe to windows rt?thanks

2018-07-13 23:46 GMT+01:00 VNNGYN <notifications@github.com>:

**Comment by VNNGYN** [comment]
No only the ones with source codes. Also, not all apps are supported on Windows RT 8.1.

**Comment by nalcwap** [comment]
ok thanks,yes i have the source but im a newbie
---------- Forwarded message ----------

**Comment by VNNGYN** [comment]
There's a guide on XDA how to compile apps. Just google it.
