### ISSUE TITLE
Any port for latest QupZilla browser for win rt ?

### ISSUE THREAD

**Issue by elhorrih** [VNNGYN/Windows-RT-8.1-Development-Tool#21]
Hi guys!
Surface RT (tegra arm32) is given a chance as a win10 version is available for it now. Yet, Edge browser is kinda slow and youtube pages are nightmare to this device with this browser. However, the old version of QupZilla ported to this platform since 2013 seems to be sleek and smooth. If only the problem of SSL issue get solved it's gonna be a relief for users of this device (which I believe it was solved in recent releases). So is there any chance that some hero ports the latest release to this rt platform?
Thank you very much for any attempt. 
Kind regards!

**Comment by VNNGYN** [comment]
Hey there!

Thank you for your message. Unfortunately, I gave up on Windows RT a long time ago and thus have no interest in porting applications to it. I am very sorry for this.

I hope you have a nice day.

Kind regards,
VNNGYN
