### ISSUE TITLE
DeSmuME 0.9.11 link broken. 

### ISSUE THREAD

**Issue by Hezy4** [VNNGYN/Windows-RT-8.1-Development-Tool#25]
Hey! 

Just wanted to report the link to download DeSmuME is broken due to zippyshare shutting down. 
Wanted to see if there was a way to fix that link. 

Thanks!

**Comment by VNNGYN** [comment]
Hey @Hezy4!

Thank you so much for letting me know. I will take a look at all the links in the next few days and see if I can do anything about it. I will keep you updated if I know more.

Stay tuned.

Kind regards,
VNNGYN

**Comment by VNNGYN** [comment]
Hey @Hezy4!

I just fixed all the links I could and removed the once I could not. DeSmuME was recoverable, but is not tested.

I hope I have helped you correctly.

Kind regards,
VNNGYN

**Comment by hooddy** [comment]
Btw 7zip available for current build
https://7-zip.org/a/7z2201-arm.exe
https://7-zip.org/a/7z2200-arm.exe
etc

Asw ell as Rufus 
https://github.com/pbatard/rufus/releases
And Keepass may be just resign to use for current version. 
And Winaero tweaker.

**Comment by Hezy4** [comment]
> Hey @Hezy4!
> 
> I just fixed all the links I could and removed the once I could not. DeSmuME was recoverable, but is not tested.
> 
> I hope I have helped you correctly.
> 
> Kind regards, VNNGYN

Thanks! I appreciate it.
