### ISSUE TITLE
Cant unstall Infected Updates manually

### ISSUE THREAD

**Issue by TommyLang** [VNNGYN/Windows-RT-8.1-Development-Tool#3]
Hi trying to boot into test mode on my surface 2 running windows rt i have gone though all the steps in the wiki and when I chose option 3 the powershell menu comes up and a pop up saying you will be logged off in 30 second then it restarts I open the desktop and try to run different 32 bit arm compiled signed apps from the xda windows 8 rt form some say that the app is not trusted, unsigned and drive maybe installed incorrectly and other apps like pantdotnet just come up with the 'this app cant be run' although other surface 2 users have  got them working also there is no watermark in the desktop. I looked at the infected updates list and some updates on the list where not uninstalled. I have tried the  Development Tool update remover 4 times but they where not removed. I also tried unstalling them though control panel but it does not work.  I am trying to uninstall them manually using wusa in cmd but i get the error (0x80073712 the component store has been corrupted) if anyone can help me thank you
Tommy

**Comment by VNNGYN** [comment]
Hi Tommy,

It seems that the component store has been corrupted. Sometimes this happens accidentally, because Windows does not remove all the files of the _Infected Updates_. You may fix this by performing a repair install or a factory reset. Please let me know how that will be going. 

Kind regards,
VNNGYN

**Comment by TommyLang** [comment]
Ok thank you i will try that and let you know

**Comment by TommyLang** [comment]
Thank you so much it worked
