### ISSUE TITLE
dev tool doesn't work!

### ISSUE THREAD

**Issue by roxas22** [VNNGYN/Windows-RT-8.1-Development-Tool#4]
As reported on title, the dev tool doesn't work. I did the removation tool and booted with "test mode", but neither already signed programs nor the signing ones work

**Comment by VNNGYN** [comment]
Do you see a watermark with "Test Mode" in the right corner of your desktop? Please keep in mind that the Development Tool will be updated at the first day of every month, which means new infected will appear after the release. Thus, the Development Tool won't work at the end of the month.

**Comment by hooddy** [comment]
@roxas22 since latest build there released new security updates. So ya need to remove latest stable and preview by yourself or wait till this tool will be update.
